const productCategory = [
    { id: 1, label: "Abrazaderas y soportes para mangueras", value: "AbrazaderasYSoportesParaMangueras" },
    { id: 2, label: "Acoplamientos de expansión", value: "AcoplamientosDeExpansion" },
    { id: 3, label: "Acoplamientos giratorios (swivel joints)", value: "AcoplamientosGiratoriosSwivelJoints" },
    { id: 4, label: "Acoplamientos para alta temperatura", value: "AcoplamientosParaAltaTemperatura" },
    { id: 5, label: "Acoplamientos rápidos hidráulicos", value: "AcoplamientosRapidosHidraulicos" },
    { id: 6, label: "Acumuladores hidráulicos", value: "AcumuladoresHidraulicos" },
    { id: 7, label: "Adaptadores de ángulo (codos)", value: "AdaptadoresDeAnguloCodos" },
    { id: 8, label: "Aceites y fluidos hidráulicos (mineral, sintético, biodegradable)", value: "AceitesYFluidosHidraulicos" },
    { id: 9, label: "Bombas hidráulicas (engranajes, pistones, paletas)", value: "BombasHidraulicas" },
    { id: 10, label: "Cilindros hidráulicos (lineales y telescópicos)", value: "CilindrosHidraulicos" },
    { id: 11, label: "Colectores y distribuidores hidráulicos", value: "ColectoresYDistribuidoresHidraulicos" },
    { id: 12, label: "Componentes de sellado (o-rings, empaques)", value: "ComponentesDeSellado" },
    { id: 13, label: "Conectores de acoplamiento rápido sin fugas", value: "ConectoresDeAcoplamientoRapidoSinFugas" },
    { id: 14, label: "Conectores de manguera multiuso", value: "ConectoresDeMangueraMultiuso" },
    { id: 15, label: "Conectores hidráulicos (acoplamientos y adaptadores)", value: "ConectoresHidraulicos" },
    { id: 16, label: "Conexiones de desconexión seca", value: "ConexionesDeDesconexionSeca" },
    { id: 17, label: "Controladores electrónicos para sistemas hidráulicos", value: "ControladoresElectronicosParaSistemasHidraulicos" },
    { id: 18, label: "Codos y tees para conexiones hidráulicas", value: "CodosYTeesParaConexionesHidraulicas" },
    { id: 19, label: "Equipos de prueba y diagnóstico hidráulico", value: "EquiposDePruebaYDiagnosticoHidraulico" },
    { id: 20, label: "Ensamblajes de mangueras personalizadas", value: "EnsamblajesDeManguerasPersonalizadas" },
    { id: 21, label: "Filtros hidráulicos (succión, presión, retorno)", value: "FiltrosHidraulicos" },
    { id: 22, label: "Filtros magnéticos para fluidos", value: "FiltrosMagneticosParaFluidos" },
    { id: 23, label: "Fundas ignífugas para mangueras", value: "FundasIgnifugasParaMangueras" },
    { id: 24, label: "Indicadores de nivel de fluido", value: "IndicadoresDeNivelDeFluido" },
    { id: 25, label: "Instrumentación (manómetros, sensores de presión)", value: "Instrumentacion" },
    { id: 26, label: "Juntas y sellos hidráulicos", value: "JuntasYSellosHidraulicos" },
    { id: 27, label: "Kit de reparación de mangueras", value: "KitDeReparacionDeMangueras" },
    { id: 28, label: "Lubricantes para acoplamientos hidráulicos", value: "LubricantesParaAcoplamientosHidraulicos" },
    { id: 29, label: "Manguitos de seguridad para mangueras", value: "ManguitosDeSeguridadParaMangueras" },
    { id: 30, label: "Mangueras de PTFE (teflón)", value: "ManguerasDePTFE" },
    { id: 31, label: "Mangueras espirales reforzadas", value: "ManguerasEspiralesReforzadas" },
    { id: 32, label: "Mangueras hidráulicas de alta presión", value: "ManguerasHidraulicasDeAltaPresion" },
    { id: 33, label: "Mangueras hidráulicas de baja presión", value: "ManguerasHidraulicasDeBajaPresion" },
    { id: 34, label: "Mangueras industriales para fluidos especiales", value: "ManguerasIndustrialesParaFluidosEspeciales" },
    { id: 35, label: "Mangueras termoplásticas", value: "ManguerasTermoplasticas" },
    { id: 36, label: "Motobombas hidráulicas", value: "MotobombasHidraulicas" },
    { id: 37, label: "Protectores para mangueras (fundas, espirales, cubiertas)", value: "ProtectoresParaMangueras" },
    { id: 38, label: "Resortes para protección de mangueras", value: "ResortesParaProteccionDeMangueras" },
    { id: 39, label: "Ruedas dentadas y piñones para sistemas hidráulicos", value: "RuedasDentadasYPinonesParaSistemasHidraulicos" },
    { id: 40, label: "Sistemas de purificación de fluidos", value: "SistemasDePurificacionDeFluidos" },
    { id: 41, label: "Sistemas de purga y limpieza de mangueras", value: "SistemasDePurgaYLimpiezaDeMangueras" },
    { id: 42, label: "Tapones y cubiertas protectoras para conexiones", value: "TaponesYCubiertasProtectorasParaConexiones" },
    { id: 43, label: "Unidades de potencia hidráulica (HPU)", value: "UnidadesDePotenciaHidraulica" },
    { id: 44, label: "Válvulas de alivio", value: "ValvulasDeAlivio" },
    { id: 45, label: "Válvulas de control de flujo", value: "ValvulasDeControlDeFlujo" },
    { id: 46, label: "Válvulas de retención", value: "ValvulasDeRetencion" },
    { id: 47, label: "Válvulas de presión hidráulica", value: "ValvulasDePresionHidraulica" },
    { id: 48, label: "Válvulas direccionales", value: "ValvulasDireccionales" },
    { id: 49, label: "Válvulas proporcionales", value: "ValvulasProporcionales" },
    { id: 50, label: "Válvulas reguladoras de presión", value: "ValvulasReguladorasDePresion" }
]


export default productCategory